function New-PSDrawIOProvider {
    <#
    .SYNOPSIS
    Scaffolds a PS.DrawIO provider or disposable fixture provider.
    .PARAMETER Name
    PascalCase provider name.
    .PARAMETER Path
    Destination directory.
    .PARAMETER Fixture
    Marks the scaffold as a test fixture and returns its manifest path.
    .EXAMPLE
    New-PSDrawIOProvider -Name PowerShell -Path ./PS.DrawIO.Provider.PowerShell
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$Path,
        [switch]$Fixture
    )

    if (-not (Test-PSDrawIOProviderNameInternal -Name $Name)) { throw "Provider name '$Name' must be PascalCase, contain only letters and numbers, and contain no dots." }
    $root = Join-Path (Resolve-Path -LiteralPath (Split-Path -Parent $Path) -ErrorAction Stop) (Split-Path -Leaf $Path)
    if (Test-Path -LiteralPath $root) { throw "Destination '$root' already exists." }
    if (-not $PSCmdlet.ShouldProcess($root, 'Create PS.DrawIO provider scaffold')) { return }

    New-Item -ItemType Directory -Path $root, (Join-Path $root 'Public'), (Join-Path $root 'Private'), (Join-Path $root 'Classes'), (Join-Path $root 'tests'), (Join-Path $root 'tests/Conformance') | Out-Null
    $manifestPath = Join-Path $root "PS.DrawIO.Provider.$Name.psd1"
    $fixtureMetadata = if ($Fixture) { "            Metadata = @{ Fixture = `$true }`n" } else { '' }
    $manifest = @"
@{
    RootModule = 'PS.DrawIO.Provider.$Name.psm1'
    ModuleVersion = '0.1.0'
    GUID = '$([guid]::NewGuid())'
    PowerShellVersion = '7.0'
    PrivateData = @{
        PSData = @{}
        PSDrawIO = @{
            ContractVersion = 1
            ProviderName = '$Name'
            Capabilities = @('Shapes')
            Shapes = @{}
$fixtureMetadata        }
    }
}
"@
    Set-Content -LiteralPath $manifestPath -Value $manifest -Encoding utf8NoBOM
    Set-Content -LiteralPath (Join-Path $root "PS.DrawIO.Provider.$Name.psm1") -Value "# Provider implementation is owned by the provider repository." -Encoding utf8NoBOM
    Set-Content -LiteralPath (Join-Path $root 'README.md') -Value "# PS.DrawIO.Provider.$Name`n`nGenerated by PS.DrawIO.Registry. Contract version: 1." -Encoding utf8NoBOM
    $conformanceTest = @'
BeforeAll {
    if ([string]::IsNullOrWhiteSpace($env:PSDRAWIO_CONFORMANCE_MANIFEST_JSON)) {
        throw "PSDRAWIO_CONFORMANCE_MANIFEST_JSON is required."
    }
    $manifest = $env:PSDRAWIO_CONFORMANCE_MANIFEST_JSON | ConvertFrom-Json
    $drawIO = $manifest.PrivateData.PSDrawIO
}

Describe 'Provider contract conformance' {
    It 'declares contract metadata' {
        $drawIO.ContractVersion | Should -Be 1
        $drawIO.ProviderName | Should -Be '__NAME__'
        @($drawIO.Capabilities).Count | Should -BeGreaterThan 0
        $drawIO.PSObject.Properties.Name | Should -Contain 'Shapes'
    }
}
'@ -replace '__NAME__', $Name
    Set-Content -LiteralPath (Join-Path $root 'tests/Conformance/Provider.Conformance.Tests.ps1') -Value $conformanceTest -Encoding utf8NoBOM
    return $manifestPath
}
